[package]
name = "vertx-rust"
version = "0.1.0"
authors = ["nerull"]
edition = "2018"

[features]
default = []

zk = ["zookeeper"]
tc = ["tcmalloc"]


[dependencies]
zookeeper = { version = "0.5.9", optional = true }
tcmalloc = { version = "0.3", optional = true }
rayon = "1.5.0"
rustc-serialize = "0.3.24"
serde = "1.0.117"
serde_json = "1.0.59"
bincode = "1.3.1"
futures = "0.3.6"
uuid = { version = "0.8", features = ["v4"] }
config = "0.10.1"
num_cpus = "1.13.0"
rand = "0.7.3"
hashbrown = "0.9.1"
lazy_static = "1.4.0"
waiter_di = "1.6.2"
hypospray = "0.1.2"
tokio-net = "0.2.0-alpha.6"
tokio = {version ="0.3.2", features = ["full"] }
hex = "0.4.2"
bytes = "0.6"
multimap = "0.8.2"
jvm-serializable = {git = "https://github.com/kathog/jvm-serializable", branch = "main"}
jvm-macro = {git = "https://github.com/kathog/jvm-serializable", branch = "main"}
log = {version = "0.4", features = ["max_level_debug", "release_max_level_info"] }
crossbeam-channel = "0.5.0"
wait-for-me = "0.2.0"

[dev-dependencies]
criterion = "0.3"
simple_logger = "1.11.0"

[[bench]]
name = "benchmarks"
harness = false