[package]
name = "vertx-rust"
version = "0.1.0"
authors = ["nerull"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.0"
rustc-serialize = "0.3.24"
serde = "1.0.117"
serde_json = "1.0.59"
bincode = "1.3.1"
futures = "0.3.6"
uuid = { version = "0.8", features = ["v4"] }
config = "0.10.1"
log = "0.4.11"
num_cpus = "1.13.0"
rand = "0.7.3"
hashbrown = "0.9.1"
lazy_static = "1.4.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmarks"
harness = false