[package]
name = "vertx-rust"
version = "0.1.0"
authors = ["Daniel Lewiński <nerull@craftsoft.eu>"]
edition = "2018"
description = "Simple Rust version of vertx tcp eventbus, tcp server and http server"
license-file = "LICENSE"
homepage = "https://github.com/kathog/vertx-rust"
repository = "https://github.com/kathog/vertx-rust"
readme = "README.md"
documentation = "https://docs.rs/vertx-rust"

[features]
default = ["client"]

zk = ["zookeeper"]
tc = ["tcmalloc"]
client = ["hyper-tls"]


[dependencies]
zookeeper = { version = "0.5.9", optional = true }
tcmalloc = { version = "0.3", optional = true }
hyper-tls = {version = "0.4", optional = true}
rayon = "1.5.0"
rustc-serialize = "0.3.24"
serde = "1.0.117"
serde_json = "1.0.59"
bincode = "1.3.1"
futures = "0.3.6"
uuid = { version = "0.8", features = ["v4"] }
config = "0.10.1"
num_cpus = "1.13.0"
rand = "0.7.3"
hashbrown = "0.9.1"
lazy_static = "1.4.0"
waiter_di = "1.6.2"
hypospray = "0.1.2"
tokio = {version ="1", features = ["full"] }
hex = "0.4.2"
bytes = "0.6"
multimap = "0.8.2"
jvm-serializable = {version = "0.0.2"}
jvm-macro = {version = "0.0.1"}
log = {version = "0.4", features = ["max_level_debug", "release_max_level_info"] }
crossbeam-channel = "0.5.0"
hyper = {version = "0.14.1", features = ["full"] }
signal-hook = "0.2.1"

[dev-dependencies]
pretty_env_logger = "0.4"
